CREATE DATABASE IF NOT EXISTS WT_AUTH;
CREATE DATABASE IF NOT EXISTS WT_PLAN;
CREATE DATABASE IF NOT EXISTS WT_EXERCISES;
CREATE DATABASE IF NOT EXISTS WT_TRACKER;
CREATE DATABASE IF NOT EXISTS WT_EMAIL;
