networks:
  wt:
    driver: bridge  

services:
  postgres:
    build: infrastructure/postgres
    networks:
      - wt
    container_name: pg    
    ports:
      - "7555:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    environment:
      - POSTGRES_PASSWORD=root

  auth-migrate:
    build: services/auth_service/migrator
    networks:
      - wt
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/wt_auth?sslmode=disable",
      "up"
    ]
  tracker-migrate:
    build: services/tracker_service/migrator
    networks:
      - wt
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/wt_tracker?sslmode=disable", "up"
    ]
  exercise-migrate:
    build: services/exercise_service/migrator
    networks:
      - wt
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/wt_exercises?sslmode=disable", "up"
    ]
  plan-migrate:
    build: services/plan_service/migrator
    networks:
      - wt
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/wt_plan?sslmode=disable", "up"
    ]
  
  email-migrate:
    build: services/email_service/migrator
    networks:
      - wt
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/wt_email?sslmode=disable", "up"
    ]
  redis:
    image: redis
    networks:
      - wt
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  rabbitmq:
    image: rabbitmq:4-management 
    networks:
      - wt
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  auth:
    build: services/auth_service
    networks:
      - wt
    ports:
      - "6001:6001"
    env_file:
      - services/auth_service/.env
    depends_on:
      redis:
        condition: service_healthy
      auth-migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
  plan:
    build: 
      context: services\plan_service
    
    command: ./main 
    networks:
      - wt
    ports:
      - "6002:6002"
    env_file:
      - services/plan_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      plan-migrate:
        condition: service_completed_successfully
  plan_consumer:
    build:
      context: services/plan_service
    command: ./consumer
    networks:
      - wt
    env_file:
      - services/plan_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      plan-migrate:
        condition: service_completed_successfully
  exercise:
    build: services\exercise_service
    networks:
      - wt
    ports:
      - 6003:6003
    env_file:
      - services/exercise_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      exercise-migrate:
        condition: service_completed_successfully
  tracker:
    build: services\tracker_service
    networks:
      - wt
    ports:
      - 6004:6004
    env_file:
      - services/tracker_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      tracker-migrate:
        condition: service_completed_successfully

  email:
    build: services\email_service
    networks:
      - wt
    env_file:
      - services/email_service/.env
    environment:
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
  orc:
    build: services\orchestration_service
    networks:
      - wt
    env_file:
      - services/orchestration_service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth-migrate:
        condition: service_completed_successfully
      tracker-migrate:
        condition: service_completed_successfully

  gateway:
    build: api_gateway
    networks:
      - wt
    ports: 
      - 5000:5000
    env_file:
      - api_gateway/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth:
        condition: service_started
      tracker:
        condition: service_started
      plan:
        condition: service_started
      exercise:
        condition: service_started
  
volumes:
  pg_data:
  redis_data: