# version: '1.1'

networks:
  wt:
    driver: bridge  

services:
  postgres:
    build: .
    networks:
      - wt
    container_name: pg    
    ports:
      - "7555:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=root

  auth-migrate:
    build: services\auth_service\migrator
    networks:
      - wt
    depends_on:
      - postgres
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/auth?sslmode=disable",
      "up"
    ]
  tracker-migrate:
    build: services\tracker_service\migrator
    networks:
      - wt
    depends_on:
      - postgres
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/tracker?sslmode=disable", "up"
    ]
  exercise-migrate:
    build: services\exercise_service\migrator
    networks:
      - wt
    depends_on:
      - postgres
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/exercise?sslmode=disable", "up"
    ]
  plan-migrate:
    build: services\plan_service\migrator
    networks:
      - wt
    depends_on:
      - postgres
    command: [
      "-path", "/migrations",
      "-database", "postgresql://postgres:root@postgres:5432/plan?sslmode=disable", "up"
    ]
  
  redis:
    image: redis
    networks:
      - wt
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  rabbitmq:
    image: rabbitmq:4-management 
    networks:
      - wt
    ports:
      - "5672:5672"
      - "15672:15672"
  auth:
    build: services\auth_service
    networks:
      - wt
    ports:
      - "6001:6001"
    environment:
      - GRPC_SERVER_ADDR=:6001
      - POSTGRES_CONN=postgresql://postgres:root@postgres:5432/auth?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=0
      - SECRET_KEY=56ekjafibaue2y8e730q8998q9h
      - SERVICE_NAME=auth_service
    depends_on:
      - redis
      - postgres
  plan:
    build: services\plan_service
    networks:
      - wt
    ports:
      - "6002:6002"
    environment:
      - GRPC_SERVER_ADDR=:6002
      - POSTGRES_CONN=postgresql://postgres:root@postgres:5432/plan?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=1
      - SECRET_KEY=56ekjafibaue2y8e730q8998q9h
      - SERVICE_NAME=plan_service
      - EXERCISE_GRPC_SERVER_ADDR=:6003
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - postgres
      - rabbitmq
  exercise:
    build: services\exercise_service
    networks:
      - wt
    ports:
      - 6003:6003
    environment:
      - GRPC_SERVER_ADDR=:6003
      - POSTGRES_CONN=postgresql://postgres:root@postgres:5432/exercise?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=2
      - SECRET_KEY=56ekjafibaue2y8e730q8998q9h
      - SERVICE_NAME=exercise_service
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - postgres
      - rabbitmq
  tracker:
    build: services\tracker_service
    networks:
      - wt
    ports:
      - 6004:6004
    environment:
      - GRPC_SERVER_ADDR=:6004
      - POSTGRES_CONN=postgresql://postgres:root@postgres:5432/tracker?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=4
      - SECRET_KEY=56ekjafibaue2y8e730q8998q9h
      - GRPC_SERVER_ADDR=:6004
      - SERVICE_NAME=tracker_service
    depends_on:
      - redis
      - postgres

  email:
    build: services\email_service
    networks:
      - wt
    environment:
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
  orc:
    build: services\orchestration_service
    networks:
      - wt
    environment:
      - AUTH_POSTGRES_CONN=postgresql://postgres:root@postgres:5432/auth?sslmode=disable
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - REDIS_DB=3
      - MQ_URL=amqp://guest:guest@rabbitmq:5672/
      - TRACKER_POSTGRES_CONN=postgresql://postgres:root@postgres:5432/tracker?sslmode=disable
    depends_on:
      - redis
      - postgres

  gateway:
    build: api_gateway
    networks:
      - wt
    ports: 
      - 5000:5000
    environment:
      - HTTP_SERVER_ADDR=:5000
      - AUTH_GRPC_CLIENT_ADDR=auth:6001
      - PLAN_GRPC_CLIENT_ADDR=plan:6002
      - EXER_GRPC_CLIENT_ADDR=exercise:6003
      - TRACKER_GRPC_CLIENT_ADDR=tracker:6004
      - SECRET_KEY=56ekjafibaue2y8e730q8998q9h
      - SERVICE_NAME=gateway
    depends_on:
      - redis
      - postgres
      - auth
      - tracker
      - plan
      - exercise
  
volumes:
  pg_data:
  redis_data: