CREATE TABLE tracker (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL,
	plan_id UUID NOT NULL,
	STARTED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ENDED_AT TIMESTAMPTZ	
);

-- CREATE TABLE workout (
-- 	tracker_id INTEGER NOT NULL,
-- 	exercise_id INTEGER NOT NULL,
-- 	set_number INTEGER NOT NULL,
-- 	weight INTEGER NOT NULL,
-- 	reps INTEGER NOT NULL
-- )