// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tracker.proto

package tracker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingTrackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingTrackReq) Reset() {
	*x = PingTrackReq{}
	mi := &file_tracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingTrackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTrackReq) ProtoMessage() {}

func (x *PingTrackReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTrackReq.ProtoReflect.Descriptor instead.
func (*PingTrackReq) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{0}
}

type PingTrackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingTrackResp) Reset() {
	*x = PingTrackResp{}
	mi := &file_tracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingTrackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTrackResp) ProtoMessage() {}

func (x *PingTrackResp) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTrackResp.ProtoReflect.Descriptor instead.
func (*PingTrackResp) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{1}
}

type EndWorkoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllExerices   []*TrackerForEachExer  `protobuf:"bytes,2,rep,name=all_exerices,json=allExerices,proto3" json:"all_exerices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndWorkoutReq) Reset() {
	*x = EndWorkoutReq{}
	mi := &file_tracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndWorkoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndWorkoutReq) ProtoMessage() {}

func (x *EndWorkoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndWorkoutReq.ProtoReflect.Descriptor instead.
func (*EndWorkoutReq) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{2}
}

func (x *EndWorkoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EndWorkoutReq) GetAllExerices() []*TrackerForEachExer {
	if x != nil {
		return x.AllExerices
	}
	return nil
}

type TrackerForEachExer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    int64                  `protobuf:"varint,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	SetsAndReps   []*SetsAndReps         `protobuf:"bytes,2,rep,name=sets_and_reps,json=setsAndReps,proto3" json:"sets_and_reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackerForEachExer) Reset() {
	*x = TrackerForEachExer{}
	mi := &file_tracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackerForEachExer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerForEachExer) ProtoMessage() {}

func (x *TrackerForEachExer) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerForEachExer.ProtoReflect.Descriptor instead.
func (*TrackerForEachExer) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *TrackerForEachExer) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *TrackerForEachExer) GetSetsAndReps() []*SetsAndReps {
	if x != nil {
		return x.SetsAndReps
	}
	return nil
}

type SetsAndReps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        int64                  `protobuf:"varint,1,opt,name=weight,proto3" json:"weight,omitempty"`
	Reps          int64                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetsAndReps) Reset() {
	*x = SetsAndReps{}
	mi := &file_tracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetsAndReps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetsAndReps) ProtoMessage() {}

func (x *SetsAndReps) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetsAndReps.ProtoReflect.Descriptor instead.
func (*SetsAndReps) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{4}
}

func (x *SetsAndReps) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *SetsAndReps) GetReps() int64 {
	if x != nil {
		return x.Reps
	}
	return 0
}

type EndWorkoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndWorkoutResp) Reset() {
	*x = EndWorkoutResp{}
	mi := &file_tracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndWorkoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndWorkoutResp) ProtoMessage() {}

func (x *EndWorkoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndWorkoutResp.ProtoReflect.Descriptor instead.
func (*EndWorkoutResp) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{5}
}

func (x *EndWorkoutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartWorkoutWithPlanReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkoutWithPlanReq) Reset() {
	*x = StartWorkoutWithPlanReq{}
	mi := &file_tracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkoutWithPlanReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkoutWithPlanReq) ProtoMessage() {}

func (x *StartWorkoutWithPlanReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkoutWithPlanReq.ProtoReflect.Descriptor instead.
func (*StartWorkoutWithPlanReq) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{6}
}

func (x *StartWorkoutWithPlanReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StartWorkoutWithPlanReq) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type StartWorkoutWithPlanResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	PlanName        string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	ExercisesInPlan []string               `protobuf:"bytes,3,rep,name=exercises_in_plan,json=exercisesInPlan,proto3" json:"exercises_in_plan,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartWorkoutWithPlanResp) Reset() {
	*x = StartWorkoutWithPlanResp{}
	mi := &file_tracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkoutWithPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkoutWithPlanResp) ProtoMessage() {}

func (x *StartWorkoutWithPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkoutWithPlanResp.ProtoReflect.Descriptor instead.
func (*StartWorkoutWithPlanResp) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{7}
}

func (x *StartWorkoutWithPlanResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartWorkoutWithPlanResp) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *StartWorkoutWithPlanResp) GetExercisesInPlan() []string {
	if x != nil {
		return x.ExercisesInPlan
	}
	return nil
}

type StartEmptyWorkoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmptyWorkoutReq) Reset() {
	*x = StartEmptyWorkoutReq{}
	mi := &file_tracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmptyWorkoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmptyWorkoutReq) ProtoMessage() {}

func (x *StartEmptyWorkoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmptyWorkoutReq.ProtoReflect.Descriptor instead.
func (*StartEmptyWorkoutReq) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{8}
}

func (x *StartEmptyWorkoutReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GeneralResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralResp) Reset() {
	*x = GeneralResp{}
	mi := &file_tracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralResp) ProtoMessage() {}

func (x *GeneralResp) ProtoReflect() protoreflect.Message {
	mi := &file_tracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralResp.ProtoReflect.Descriptor instead.
func (*GeneralResp) Descriptor() ([]byte, []int) {
	return file_tracker_proto_rawDescGZIP(), []int{9}
}

func (x *GeneralResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_tracker_proto protoreflect.FileDescriptor

const file_tracker_proto_rawDesc = "" +
	"\n" +
	"\rtracker.proto\x12\x05proto\"\x0e\n" +
	"\fPingTrackReq\"\x0f\n" +
	"\rPingTrackResp\"f\n" +
	"\rEndWorkoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12<\n" +
	"\fall_exerices\x18\x02 \x03(\v2\x19.proto.TrackerForEachExerR\vallExerices\"m\n" +
	"\x12TrackerForEachExer\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\x03R\n" +
	"exerciseId\x126\n" +
	"\rsets_and_reps\x18\x02 \x03(\v2\x12.proto.SetsAndRepsR\vsetsAndReps\"9\n" +
	"\vSetsAndReps\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x03R\x06weight\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x03R\x04reps\"*\n" +
	"\x0eEndWorkoutResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"O\n" +
	"\x17StartWorkoutWithPlanReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\"}\n" +
	"\x18StartWorkoutWithPlanResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12*\n" +
	"\x11exercises_in_plan\x18\x03 \x03(\tR\x0fexercisesInPlan\"/\n" +
	"\x14StartEmptyWorkoutReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"'\n" +
	"\vGeneralResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa5\x02\n" +
	"\x0eTrackerService\x12F\n" +
	"\x11StartEmptyWorkout\x12\x1b.proto.StartEmptyWorkoutReq\x1a\x12.proto.GeneralResp\"\x00\x12Y\n" +
	"\x14StartWorkoutWithPlan\x12\x1e.proto.StartWorkoutWithPlanReq\x1a\x1f.proto.StartWorkoutWithPlanResp\"\x00\x12;\n" +
	"\n" +
	"EndWorkout\x12\x14.proto.EndWorkoutReq\x1a\x15.proto.EndWorkoutResp\"\x00\x123\n" +
	"\x04PING\x12\x13.proto.PingTrackReq\x1a\x14.proto.PingTrackResp\"\x00B\x10Z\x0eshared/trackerb\x06proto3"

var (
	file_tracker_proto_rawDescOnce sync.Once
	file_tracker_proto_rawDescData []byte
)

func file_tracker_proto_rawDescGZIP() []byte {
	file_tracker_proto_rawDescOnce.Do(func() {
		file_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)))
	})
	return file_tracker_proto_rawDescData
}

var file_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tracker_proto_goTypes = []any{
	(*PingTrackReq)(nil),             // 0: proto.PingTrackReq
	(*PingTrackResp)(nil),            // 1: proto.PingTrackResp
	(*EndWorkoutReq)(nil),            // 2: proto.EndWorkoutReq
	(*TrackerForEachExer)(nil),       // 3: proto.TrackerForEachExer
	(*SetsAndReps)(nil),              // 4: proto.SetsAndReps
	(*EndWorkoutResp)(nil),           // 5: proto.EndWorkoutResp
	(*StartWorkoutWithPlanReq)(nil),  // 6: proto.StartWorkoutWithPlanReq
	(*StartWorkoutWithPlanResp)(nil), // 7: proto.StartWorkoutWithPlanResp
	(*StartEmptyWorkoutReq)(nil),     // 8: proto.StartEmptyWorkoutReq
	(*GeneralResp)(nil),              // 9: proto.GeneralResp
}
var file_tracker_proto_depIdxs = []int32{
	3, // 0: proto.EndWorkoutReq.all_exerices:type_name -> proto.TrackerForEachExer
	4, // 1: proto.TrackerForEachExer.sets_and_reps:type_name -> proto.SetsAndReps
	8, // 2: proto.TrackerService.StartEmptyWorkout:input_type -> proto.StartEmptyWorkoutReq
	6, // 3: proto.TrackerService.StartWorkoutWithPlan:input_type -> proto.StartWorkoutWithPlanReq
	2, // 4: proto.TrackerService.EndWorkout:input_type -> proto.EndWorkoutReq
	0, // 5: proto.TrackerService.PING:input_type -> proto.PingTrackReq
	9, // 6: proto.TrackerService.StartEmptyWorkout:output_type -> proto.GeneralResp
	7, // 7: proto.TrackerService.StartWorkoutWithPlan:output_type -> proto.StartWorkoutWithPlanResp
	5, // 8: proto.TrackerService.EndWorkout:output_type -> proto.EndWorkoutResp
	1, // 9: proto.TrackerService.PING:output_type -> proto.PingTrackResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tracker_proto_init() }
func file_tracker_proto_init() {
	if File_tracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tracker_proto_rawDesc), len(file_tracker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tracker_proto_goTypes,
		DependencyIndexes: file_tracker_proto_depIdxs,
		MessageInfos:      file_tracker_proto_msgTypes,
	}.Build()
	File_tracker_proto = out.File
	file_tracker_proto_goTypes = nil
	file_tracker_proto_depIdxs = nil
}
