// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: plan.proto

package plan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlanService_PlanExistsReturnId_FullMethodName   = "/proto.PlanService/PlanExistsReturnId"
	PlanService_PlanExistsReturnPlan_FullMethodName = "/proto.PlanService/PlanExistsReturnPlan"
	PlanService_GetEmptyPlanId_FullMethodName       = "/proto.PlanService/GetEmptyPlanId"
	PlanService_CreateEmptyPlan_FullMethodName      = "/proto.PlanService/CreateEmptyPlan"
)

// PlanServiceClient is the client API for PlanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanServiceClient interface {
	// plan_name, user_id -> exists, plan_id
	PlanExistsReturnId(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsResp, error)
	// plan_name, user_id -> exits, plan_id, exercise_ids
	PlanExistsReturnPlan(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsReturnPlanResp, error)
	// user_id -> empty_plan_id
	GetEmptyPlanId(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*EmptyPlanIdResp, error)
	CreateEmptyPlan(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*CreateEmptyPlanResp, error)
}

type planServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanServiceClient(cc grpc.ClientConnInterface) PlanServiceClient {
	return &planServiceClient{cc}
}

func (c *planServiceClient) PlanExistsReturnId(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanExistsResp)
	err := c.cc.Invoke(ctx, PlanService_PlanExistsReturnId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) PlanExistsReturnPlan(ctx context.Context, in *SendPlanName, opts ...grpc.CallOption) (*PlanExistsReturnPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanExistsReturnPlanResp)
	err := c.cc.Invoke(ctx, PlanService_PlanExistsReturnPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) GetEmptyPlanId(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*EmptyPlanIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyPlanIdResp)
	err := c.cc.Invoke(ctx, PlanService_GetEmptyPlanId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planServiceClient) CreateEmptyPlan(ctx context.Context, in *SendUserID, opts ...grpc.CallOption) (*CreateEmptyPlanResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEmptyPlanResp)
	err := c.cc.Invoke(ctx, PlanService_CreateEmptyPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanServiceServer is the server API for PlanService service.
// All implementations must embed UnimplementedPlanServiceServer
// for forward compatibility.
type PlanServiceServer interface {
	// plan_name, user_id -> exists, plan_id
	PlanExistsReturnId(context.Context, *SendPlanName) (*PlanExistsResp, error)
	// plan_name, user_id -> exits, plan_id, exercise_ids
	PlanExistsReturnPlan(context.Context, *SendPlanName) (*PlanExistsReturnPlanResp, error)
	// user_id -> empty_plan_id
	GetEmptyPlanId(context.Context, *SendUserID) (*EmptyPlanIdResp, error)
	CreateEmptyPlan(context.Context, *SendUserID) (*CreateEmptyPlanResp, error)
	mustEmbedUnimplementedPlanServiceServer()
}

// UnimplementedPlanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlanServiceServer struct{}

func (UnimplementedPlanServiceServer) PlanExistsReturnId(context.Context, *SendPlanName) (*PlanExistsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanExistsReturnId not implemented")
}
func (UnimplementedPlanServiceServer) PlanExistsReturnPlan(context.Context, *SendPlanName) (*PlanExistsReturnPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanExistsReturnPlan not implemented")
}
func (UnimplementedPlanServiceServer) GetEmptyPlanId(context.Context, *SendUserID) (*EmptyPlanIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmptyPlanId not implemented")
}
func (UnimplementedPlanServiceServer) CreateEmptyPlan(context.Context, *SendUserID) (*CreateEmptyPlanResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEmptyPlan not implemented")
}
func (UnimplementedPlanServiceServer) mustEmbedUnimplementedPlanServiceServer() {}
func (UnimplementedPlanServiceServer) testEmbeddedByValue()                     {}

// UnsafePlanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanServiceServer will
// result in compilation errors.
type UnsafePlanServiceServer interface {
	mustEmbedUnimplementedPlanServiceServer()
}

func RegisterPlanServiceServer(s grpc.ServiceRegistrar, srv PlanServiceServer) {
	// If the following call panics, it indicates UnimplementedPlanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlanService_ServiceDesc, srv)
}

func _PlanService_PlanExistsReturnId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlanName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).PlanExistsReturnId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_PlanExistsReturnId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).PlanExistsReturnId(ctx, req.(*SendPlanName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_PlanExistsReturnPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPlanName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).PlanExistsReturnPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_PlanExistsReturnPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).PlanExistsReturnPlan(ctx, req.(*SendPlanName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_GetEmptyPlanId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).GetEmptyPlanId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_GetEmptyPlanId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).GetEmptyPlanId(ctx, req.(*SendUserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanService_CreateEmptyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanServiceServer).CreateEmptyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlanService_CreateEmptyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanServiceServer).CreateEmptyPlan(ctx, req.(*SendUserID))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanService_ServiceDesc is the grpc.ServiceDesc for PlanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PlanService",
	HandlerType: (*PlanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanExistsReturnId",
			Handler:    _PlanService_PlanExistsReturnId_Handler,
		},
		{
			MethodName: "PlanExistsReturnPlan",
			Handler:    _PlanService_PlanExistsReturnPlan_Handler,
		},
		{
			MethodName: "GetEmptyPlanId",
			Handler:    _PlanService_GetEmptyPlanId_Handler,
		},
		{
			MethodName: "CreateEmptyPlan",
			Handler:    _PlanService_CreateEmptyPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plan.proto",
}
