// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: plan.proto

package plan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendUserID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserID) Reset() {
	*x = SendUserID{}
	mi := &file_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserID) ProtoMessage() {}

func (x *SendUserID) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserID.ProtoReflect.Descriptor instead.
func (*SendUserID) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{0}
}

func (x *SendUserID) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateEmptyPlanResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmptyPlanResp) Reset() {
	*x = CreateEmptyPlanResp{}
	mi := &file_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmptyPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyPlanResp) ProtoMessage() {}

func (x *CreateEmptyPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyPlanResp.ProtoReflect.Descriptor instead.
func (*CreateEmptyPlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmptyPlanResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmptyPlanIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmptyPlanId   int64                  `protobuf:"varint,1,opt,name=empty_plan_id,json=emptyPlanId,proto3" json:"empty_plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPlanIdResp) Reset() {
	*x = EmptyPlanIdResp{}
	mi := &file_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPlanIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPlanIdResp) ProtoMessage() {}

func (x *EmptyPlanIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPlanIdResp.ProtoReflect.Descriptor instead.
func (*EmptyPlanIdResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{2}
}

func (x *EmptyPlanIdResp) GetEmptyPlanId() int64 {
	if x != nil {
		return x.EmptyPlanId
	}
	return 0
}

type SendPlanName struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanName      string `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlanName) Reset() {
	*x = SendPlanName{}
	mi := &file_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlanName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlanName) ProtoMessage() {}

func (x *SendPlanName) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlanName.ProtoReflect.Descriptor instead.
func (*SendPlanName) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{3}
}

func (x *SendPlanName) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendPlanName) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

type PlanExistsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PlanId        int64                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExistsResp) Reset() {
	*x = PlanExistsResp{}
	mi := &file_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExistsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExistsResp) ProtoMessage() {}

func (x *PlanExistsResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExistsResp.ProtoReflect.Descriptor instead.
func (*PlanExistsResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{4}
}

func (x *PlanExistsResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *PlanExistsResp) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type PlanExistsReturnPlanResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	PlanId int64 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	ExerciseIds   []int64 `protobuf:"varint,3,rep,packed,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanExistsReturnPlanResp) Reset() {
	*x = PlanExistsReturnPlanResp{}
	mi := &file_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanExistsReturnPlanResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanExistsReturnPlanResp) ProtoMessage() {}

func (x *PlanExistsReturnPlanResp) ProtoReflect() protoreflect.Message {
	mi := &file_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanExistsReturnPlanResp.ProtoReflect.Descriptor instead.
func (*PlanExistsReturnPlanResp) Descriptor() ([]byte, []int) {
	return file_plan_proto_rawDescGZIP(), []int{5}
}

func (x *PlanExistsReturnPlanResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *PlanExistsReturnPlanResp) GetPlanId() int64 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *PlanExistsReturnPlanResp) GetExerciseIds() []int64 {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

var File_plan_proto protoreflect.FileDescriptor

const file_plan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"plan.proto\x12\x05proto\"%\n" +
	"\n" +
	"SendUserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"/\n" +
	"\x13CreateEmptyPlanResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"5\n" +
	"\x0fEmptyPlanIdResp\x12\"\n" +
	"\rempty_plan_id\x18\x01 \x01(\x03R\vemptyPlanId\"D\n" +
	"\fSendPlanName\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\"A\n" +
	"\x0ePlanExistsResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x03R\x06planId\"n\n" +
	"\x18PlanExistsReturnPlanResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x03R\x06planId\x12!\n" +
	"\fexercise_ids\x18\x03 \x03(\x03R\vexerciseIds2\xa4\x02\n" +
	"\vPlanService\x12B\n" +
	"\x12PlanExistsReturnId\x12\x13.proto.SendPlanName\x1a\x15.proto.PlanExistsResp\"\x00\x12N\n" +
	"\x14PlanExistsReturnPlan\x12\x13.proto.SendPlanName\x1a\x1f.proto.PlanExistsReturnPlanResp\"\x00\x12=\n" +
	"\x0eGetEmptyPlanId\x12\x11.proto.SendUserID\x1a\x16.proto.EmptyPlanIdResp\"\x00\x12B\n" +
	"\x0fCreateEmptyPlan\x12\x11.proto.SendUserID\x1a\x1a.proto.CreateEmptyPlanResp\"\x00B\x0eZ\f/shared/planb\x06proto3"

var (
	file_plan_proto_rawDescOnce sync.Once
	file_plan_proto_rawDescData []byte
)

func file_plan_proto_rawDescGZIP() []byte {
	file_plan_proto_rawDescOnce.Do(func() {
		file_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)))
	})
	return file_plan_proto_rawDescData
}

var file_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plan_proto_goTypes = []any{
	(*SendUserID)(nil),               // 0: proto.SendUserID
	(*CreateEmptyPlanResp)(nil),      // 1: proto.CreateEmptyPlanResp
	(*EmptyPlanIdResp)(nil),          // 2: proto.EmptyPlanIdResp
	(*SendPlanName)(nil),             // 3: proto.SendPlanName
	(*PlanExistsResp)(nil),           // 4: proto.PlanExistsResp
	(*PlanExistsReturnPlanResp)(nil), // 5: proto.PlanExistsReturnPlanResp
}
var file_plan_proto_depIdxs = []int32{
	3, // 0: proto.PlanService.PlanExistsReturnId:input_type -> proto.SendPlanName
	3, // 1: proto.PlanService.PlanExistsReturnPlan:input_type -> proto.SendPlanName
	0, // 2: proto.PlanService.GetEmptyPlanId:input_type -> proto.SendUserID
	0, // 3: proto.PlanService.CreateEmptyPlan:input_type -> proto.SendUserID
	4, // 4: proto.PlanService.PlanExistsReturnId:output_type -> proto.PlanExistsResp
	5, // 5: proto.PlanService.PlanExistsReturnPlan:output_type -> proto.PlanExistsReturnPlanResp
	2, // 6: proto.PlanService.GetEmptyPlanId:output_type -> proto.EmptyPlanIdResp
	1, // 7: proto.PlanService.CreateEmptyPlan:output_type -> proto.CreateEmptyPlanResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plan_proto_init() }
func file_plan_proto_init() {
	if File_plan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_proto_rawDesc), len(file_plan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plan_proto_goTypes,
		DependencyIndexes: file_plan_proto_depIdxs,
		MessageInfos:      file_plan_proto_msgTypes,
	}.Build()
	File_plan_proto = out.File
	file_plan_proto_goTypes = nil
	file_plan_proto_depIdxs = nil
}
