// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: exercise.proto

package exercise

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendExerciseName struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExerciseName) Reset() {
	*x = SendExerciseName{}
	mi := &file_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExerciseName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExerciseName) ProtoMessage() {}

func (x *SendExerciseName) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExerciseName.ProtoReflect.Descriptor instead.
func (*SendExerciseName) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{0}
}

func (x *SendExerciseName) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

type ExerciseExitsResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseExitsResp) Reset() {
	*x = ExerciseExitsResp{}
	mi := &file_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseExitsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseExitsResp) ProtoMessage() {}

func (x *ExerciseExitsResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseExitsResp.ProtoReflect.Descriptor instead.
func (*ExerciseExitsResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *ExerciseExitsResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetExerciseIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    int32                  `protobuf:"varint,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseIdResp) Reset() {
	*x = GetExerciseIdResp{}
	mi := &file_exercise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseIdResp) ProtoMessage() {}

func (x *GetExerciseIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseIdResp.ProtoReflect.Descriptor instead.
func (*GetExerciseIdResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{2}
}

func (x *GetExerciseIdResp) GetExerciseId() int32 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

type ExerciseExistsReturnIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ExerciseId    int32                  `protobuf:"varint,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseExistsReturnIdResp) Reset() {
	*x = ExerciseExistsReturnIdResp{}
	mi := &file_exercise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseExistsReturnIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseExistsReturnIdResp) ProtoMessage() {}

func (x *ExerciseExistsReturnIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseExistsReturnIdResp.ProtoReflect.Descriptor instead.
func (*ExerciseExistsReturnIdResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{3}
}

func (x *ExerciseExistsReturnIdResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExerciseExistsReturnIdResp) GetExerciseId() int32 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

var File_exercise_proto protoreflect.FileDescriptor

const file_exercise_proto_rawDesc = "" +
	"\n" +
	"\x0eexercise.proto\x12\x05proto\"7\n" +
	"\x10SendExerciseName\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"+\n" +
	"\x11ExerciseExitsResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"4\n" +
	"\x11GetExerciseIdResp\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\x05R\n" +
	"exerciseId\"U\n" +
	"\x1aExerciseExistsReturnIdResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\x05R\n" +
	"exerciseId2i\n" +
	"\x0fExerciseService\x12V\n" +
	"\x16ExerciseExistsReturnId\x12\x17.proto.SendExerciseName\x1a!.proto.ExerciseExistsReturnIdResp\"\x00B\x12Z\x10/shared/exerciseb\x06proto3"

var (
	file_exercise_proto_rawDescOnce sync.Once
	file_exercise_proto_rawDescData []byte
)

func file_exercise_proto_rawDescGZIP() []byte {
	file_exercise_proto_rawDescOnce.Do(func() {
		file_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)))
	})
	return file_exercise_proto_rawDescData
}

var file_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_exercise_proto_goTypes = []any{
	(*SendExerciseName)(nil),           // 0: proto.SendExerciseName
	(*ExerciseExitsResp)(nil),          // 1: proto.ExerciseExitsResp
	(*GetExerciseIdResp)(nil),          // 2: proto.GetExerciseIdResp
	(*ExerciseExistsReturnIdResp)(nil), // 3: proto.ExerciseExistsReturnIdResp
}
var file_exercise_proto_depIdxs = []int32{
	0, // 0: proto.ExerciseService.ExerciseExistsReturnId:input_type -> proto.SendExerciseName
	3, // 1: proto.ExerciseService.ExerciseExistsReturnId:output_type -> proto.ExerciseExistsReturnIdResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_exercise_proto_init() }
func file_exercise_proto_init() {
	if File_exercise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_proto_goTypes,
		DependencyIndexes: file_exercise_proto_depIdxs,
		MessageInfos:      file_exercise_proto_msgTypes,
	}.Build()
	File_exercise_proto = out.File
	file_exercise_proto_goTypes = nil
	file_exercise_proto_depIdxs = nil
}
