// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: exercise.proto

package exercise

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthReq) Reset() {
	*x = GetHealthReq{}
	mi := &file_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthReq) ProtoMessage() {}

func (x *GetHealthReq) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthReq.ProtoReflect.Descriptor instead.
func (*GetHealthReq) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{0}
}

type GetHealthResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceName      string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status           string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PostgresRespTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=postgres_resp_time,json=postgresRespTime,proto3" json:"postgres_resp_time,omitempty"`
	RedisRespTime    *durationpb.Duration   `protobuf:"bytes,4,opt,name=redis_resp_time,json=redisRespTime,proto3" json:"redis_resp_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetHealthResp) Reset() {
	*x = GetHealthResp{}
	mi := &file_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResp) ProtoMessage() {}

func (x *GetHealthResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResp.ProtoReflect.Descriptor instead.
func (*GetHealthResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *GetHealthResp) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetHealthResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResp) GetPostgresRespTime() *durationpb.Duration {
	if x != nil {
		return x.PostgresRespTime
	}
	return nil
}

func (x *GetHealthResp) GetRedisRespTime() *durationpb.Duration {
	if x != nil {
		return x.RedisRespTime
	}
	return nil
}

type PingExerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingExerReq) Reset() {
	*x = PingExerReq{}
	mi := &file_exercise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingExerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingExerReq) ProtoMessage() {}

func (x *PingExerReq) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingExerReq.ProtoReflect.Descriptor instead.
func (*PingExerReq) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{2}
}

type PingExerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingExerResp) Reset() {
	*x = PingExerResp{}
	mi := &file_exercise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingExerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingExerResp) ProtoMessage() {}

func (x *PingExerResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingExerResp.ProtoReflect.Descriptor instead.
func (*PingExerResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{3}
}

type CreateExerciseReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	BodyPart      string                 `protobuf:"bytes,2,opt,name=body_part,json=bodyPart,proto3" json:"body_part,omitempty"`
	Equipment     string                 `protobuf:"bytes,3,opt,name=equipment,proto3" json:"equipment,omitempty"`
	RestTime      int64                  `protobuf:"varint,4,opt,name=rest_time,json=restTime,proto3" json:"rest_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExerciseReq) Reset() {
	*x = CreateExerciseReq{}
	mi := &file_exercise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseReq) ProtoMessage() {}

func (x *CreateExerciseReq) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseReq.ProtoReflect.Descriptor instead.
func (*CreateExerciseReq) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{4}
}

func (x *CreateExerciseReq) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *CreateExerciseReq) GetBodyPart() string {
	if x != nil {
		return x.BodyPart
	}
	return ""
}

func (x *CreateExerciseReq) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *CreateExerciseReq) GetRestTime() int64 {
	if x != nil {
		return x.RestTime
	}
	return 0
}

type CreateExerciseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Exercise      *OneExerciseResp       `protobuf:"bytes,2,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExerciseResp) Reset() {
	*x = CreateExerciseResp{}
	mi := &file_exercise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseResp) ProtoMessage() {}

func (x *CreateExerciseResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseResp.ProtoReflect.Descriptor instead.
func (*CreateExerciseResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExerciseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateExerciseResp) GetExercise() *OneExerciseResp {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type DeleteExerciseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExerciseResp) Reset() {
	*x = DeleteExerciseResp{}
	mi := &file_exercise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExerciseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExerciseResp) ProtoMessage() {}

func (x *DeleteExerciseResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExerciseResp.ProtoReflect.Descriptor instead.
func (*DeleteExerciseResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteExerciseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendExerciseName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExerciseName) Reset() {
	*x = SendExerciseName{}
	mi := &file_exercise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExerciseName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExerciseName) ProtoMessage() {}

func (x *SendExerciseName) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExerciseName.ProtoReflect.Descriptor instead.
func (*SendExerciseName) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{7}
}

func (x *SendExerciseName) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

type ExerciseExistsReturnIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ExerciseId    int32                  `protobuf:"varint,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseExistsReturnIdResp) Reset() {
	*x = ExerciseExistsReturnIdResp{}
	mi := &file_exercise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseExistsReturnIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseExistsReturnIdResp) ProtoMessage() {}

func (x *ExerciseExistsReturnIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseExistsReturnIdResp.ProtoReflect.Descriptor instead.
func (*ExerciseExistsReturnIdResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{8}
}

func (x *ExerciseExistsReturnIdResp) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *ExerciseExistsReturnIdResp) GetExerciseId() int32 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

type SendExerciseID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId    int64                  `protobuf:"varint,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExerciseID) Reset() {
	*x = SendExerciseID{}
	mi := &file_exercise_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExerciseID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExerciseID) ProtoMessage() {}

func (x *SendExerciseID) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExerciseID.ProtoReflect.Descriptor instead.
func (*SendExerciseID) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{9}
}

func (x *SendExerciseID) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

type GetExerciseNameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExerciseName  string                 `protobuf:"bytes,1,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseNameResp) Reset() {
	*x = GetExerciseNameResp{}
	mi := &file_exercise_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseNameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseNameResp) ProtoMessage() {}

func (x *GetExerciseNameResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseNameResp.ProtoReflect.Descriptor instead.
func (*GetExerciseNameResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{10}
}

func (x *GetExerciseNameResp) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

type GetAllExercisesREq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExercisesREq) Reset() {
	*x = GetAllExercisesREq{}
	mi := &file_exercise_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExercisesREq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExercisesREq) ProtoMessage() {}

func (x *GetAllExercisesREq) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExercisesREq.ProtoReflect.Descriptor instead.
func (*GetAllExercisesREq) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{11}
}

type GetAllExercisesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllExericses  []*OneExerciseResp     `protobuf:"bytes,1,rep,name=all_exericses,json=allExericses,proto3" json:"all_exericses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExercisesResp) Reset() {
	*x = GetAllExercisesResp{}
	mi := &file_exercise_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExercisesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExercisesResp) ProtoMessage() {}

func (x *GetAllExercisesResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExercisesResp.ProtoReflect.Descriptor instead.
func (*GetAllExercisesResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllExercisesResp) GetAllExericses() []*OneExerciseResp {
	if x != nil {
		return x.AllExericses
	}
	return nil
}

type OneExerciseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RestTime      int64                  `protobuf:"varint,3,opt,name=rest_time,json=restTime,proto3" json:"rest_time,omitempty"`
	BodyPart      string                 `protobuf:"bytes,4,opt,name=body_part,json=bodyPart,proto3" json:"body_part,omitempty"`
	Equipment     string                 `protobuf:"bytes,5,opt,name=equipment,proto3" json:"equipment,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneExerciseResp) Reset() {
	*x = OneExerciseResp{}
	mi := &file_exercise_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneExerciseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneExerciseResp) ProtoMessage() {}

func (x *OneExerciseResp) ProtoReflect() protoreflect.Message {
	mi := &file_exercise_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneExerciseResp.ProtoReflect.Descriptor instead.
func (*OneExerciseResp) Descriptor() ([]byte, []int) {
	return file_exercise_proto_rawDescGZIP(), []int{13}
}

func (x *OneExerciseResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OneExerciseResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OneExerciseResp) GetRestTime() int64 {
	if x != nil {
		return x.RestTime
	}
	return 0
}

func (x *OneExerciseResp) GetBodyPart() string {
	if x != nil {
		return x.BodyPart
	}
	return ""
}

func (x *OneExerciseResp) GetEquipment() string {
	if x != nil {
		return x.Equipment
	}
	return ""
}

func (x *OneExerciseResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_exercise_proto protoreflect.FileDescriptor

const file_exercise_proto_rawDesc = "" +
	"\n" +
	"\x0eexercise.proto\x12\bexercise\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x0e\n" +
	"\fGetHealthReq\"\xd6\x01\n" +
	"\rGetHealthResp\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12G\n" +
	"\x12postgres_resp_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10postgresRespTime\x12A\n" +
	"\x0fredis_resp_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rredisRespTime\"\r\n" +
	"\vPingExerReq\"\x0e\n" +
	"\fPingExerResp\"\x90\x01\n" +
	"\x11CreateExerciseReq\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\x12\x1b\n" +
	"\tbody_part\x18\x02 \x01(\tR\bbodyPart\x12\x1c\n" +
	"\tequipment\x18\x03 \x01(\tR\tequipment\x12\x1b\n" +
	"\trest_time\x18\x04 \x01(\x03R\brestTime\"e\n" +
	"\x12CreateExerciseResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x125\n" +
	"\bexercise\x18\x02 \x01(\v2\x19.exercise.OneExerciseRespR\bexercise\".\n" +
	"\x12DeleteExerciseResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x10SendExerciseName\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"U\n" +
	"\x1aExerciseExistsReturnIdResp\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\x05R\n" +
	"exerciseId\"1\n" +
	"\x0eSendExerciseID\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\x03R\n" +
	"exerciseId\":\n" +
	"\x13GetExerciseNameResp\x12#\n" +
	"\rexercise_name\x18\x01 \x01(\tR\fexerciseName\"\x14\n" +
	"\x12GetAllExercisesREq\"U\n" +
	"\x13GetAllExercisesResp\x12>\n" +
	"\rall_exericses\x18\x01 \x03(\v2\x19.exercise.OneExerciseRespR\fallExericses\"\xc8\x01\n" +
	"\x0fOneExerciseResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\trest_time\x18\x03 \x01(\x03R\brestTime\x12\x1b\n" +
	"\tbody_part\x18\x04 \x01(\tR\bbodyPart\x12\x1c\n" +
	"\tequipment\x18\x05 \x01(\tR\tequipment\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xf0\x04\n" +
	"\x0fExerciseService\x12\\\n" +
	"\x16ExerciseExistsReturnId\x12\x1a.exercise.SendExerciseName\x1a$.exercise.ExerciseExistsReturnIdResp\"\x00\x12L\n" +
	"\x0fGetExerciseName\x12\x18.exercise.SendExerciseID\x1a\x1d.exercise.GetExerciseNameResp\"\x00\x12P\n" +
	"\x0fGetAllExercises\x12\x1c.exercise.GetAllExercisesREq\x1a\x1d.exercise.GetAllExercisesResp\"\x00\x12I\n" +
	"\x0eGetOneExercise\x12\x1a.exercise.SendExerciseName\x1a\x19.exercise.OneExerciseResp\"\x00\x12M\n" +
	"\x0eCreateExercise\x12\x1b.exercise.CreateExerciseReq\x1a\x1c.exercise.CreateExerciseResp\"\x00\x12L\n" +
	"\x0eDeleteExercise\x12\x1a.exercise.SendExerciseName\x1a\x1c.exercise.DeleteExerciseResp\"\x00\x127\n" +
	"\x04PING\x12\x15.exercise.PingExerReq\x1a\x16.exercise.PingExerResp\"\x00\x12>\n" +
	"\tGetHealth\x12\x16.exercise.GetHealthReq\x1a\x17.exercise.GetHealthResp\"\x00B\x12Z\x10/shared/exerciseb\x06proto3"

var (
	file_exercise_proto_rawDescOnce sync.Once
	file_exercise_proto_rawDescData []byte
)

func file_exercise_proto_rawDescGZIP() []byte {
	file_exercise_proto_rawDescOnce.Do(func() {
		file_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)))
	})
	return file_exercise_proto_rawDescData
}

var file_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_exercise_proto_goTypes = []any{
	(*GetHealthReq)(nil),               // 0: exercise.GetHealthReq
	(*GetHealthResp)(nil),              // 1: exercise.GetHealthResp
	(*PingExerReq)(nil),                // 2: exercise.PingExerReq
	(*PingExerResp)(nil),               // 3: exercise.PingExerResp
	(*CreateExerciseReq)(nil),          // 4: exercise.CreateExerciseReq
	(*CreateExerciseResp)(nil),         // 5: exercise.CreateExerciseResp
	(*DeleteExerciseResp)(nil),         // 6: exercise.DeleteExerciseResp
	(*SendExerciseName)(nil),           // 7: exercise.SendExerciseName
	(*ExerciseExistsReturnIdResp)(nil), // 8: exercise.ExerciseExistsReturnIdResp
	(*SendExerciseID)(nil),             // 9: exercise.SendExerciseID
	(*GetExerciseNameResp)(nil),        // 10: exercise.GetExerciseNameResp
	(*GetAllExercisesREq)(nil),         // 11: exercise.GetAllExercisesREq
	(*GetAllExercisesResp)(nil),        // 12: exercise.GetAllExercisesResp
	(*OneExerciseResp)(nil),            // 13: exercise.OneExerciseResp
	(*durationpb.Duration)(nil),        // 14: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_exercise_proto_depIdxs = []int32{
	14, // 0: exercise.GetHealthResp.postgres_resp_time:type_name -> google.protobuf.Duration
	14, // 1: exercise.GetHealthResp.redis_resp_time:type_name -> google.protobuf.Duration
	13, // 2: exercise.CreateExerciseResp.exercise:type_name -> exercise.OneExerciseResp
	13, // 3: exercise.GetAllExercisesResp.all_exericses:type_name -> exercise.OneExerciseResp
	15, // 4: exercise.OneExerciseResp.created_at:type_name -> google.protobuf.Timestamp
	7,  // 5: exercise.ExerciseService.ExerciseExistsReturnId:input_type -> exercise.SendExerciseName
	9,  // 6: exercise.ExerciseService.GetExerciseName:input_type -> exercise.SendExerciseID
	11, // 7: exercise.ExerciseService.GetAllExercises:input_type -> exercise.GetAllExercisesREq
	7,  // 8: exercise.ExerciseService.GetOneExercise:input_type -> exercise.SendExerciseName
	4,  // 9: exercise.ExerciseService.CreateExercise:input_type -> exercise.CreateExerciseReq
	7,  // 10: exercise.ExerciseService.DeleteExercise:input_type -> exercise.SendExerciseName
	2,  // 11: exercise.ExerciseService.PING:input_type -> exercise.PingExerReq
	0,  // 12: exercise.ExerciseService.GetHealth:input_type -> exercise.GetHealthReq
	8,  // 13: exercise.ExerciseService.ExerciseExistsReturnId:output_type -> exercise.ExerciseExistsReturnIdResp
	10, // 14: exercise.ExerciseService.GetExerciseName:output_type -> exercise.GetExerciseNameResp
	12, // 15: exercise.ExerciseService.GetAllExercises:output_type -> exercise.GetAllExercisesResp
	13, // 16: exercise.ExerciseService.GetOneExercise:output_type -> exercise.OneExerciseResp
	5,  // 17: exercise.ExerciseService.CreateExercise:output_type -> exercise.CreateExerciseResp
	6,  // 18: exercise.ExerciseService.DeleteExercise:output_type -> exercise.DeleteExerciseResp
	3,  // 19: exercise.ExerciseService.PING:output_type -> exercise.PingExerResp
	1,  // 20: exercise.ExerciseService.GetHealth:output_type -> exercise.GetHealthResp
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_exercise_proto_init() }
func file_exercise_proto_init() {
	if File_exercise_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exercise_proto_rawDesc), len(file_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exercise_proto_goTypes,
		DependencyIndexes: file_exercise_proto_depIdxs,
		MessageInfos:      file_exercise_proto_msgTypes,
	}.Build()
	File_exercise_proto = out.File
	file_exercise_proto_goTypes = nil
	file_exercise_proto_depIdxs = nil
}
