CREATE TABLE PUSH_TO_QUEUE_FAILED(
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	target_service TEXT NOT NULL,
	target_db_id UUID NOT NULL,
    task_name TEXT NOT NULL,
	status TEXT NOT NULL,
	number_of_tries INTEGER NOT NULL,
    LAST_TRIED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
)