CREATE TABLE PLANS(
	ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	USER_ID UUID NOT NULL,
	NAME TEXT NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX one_user_one_plan_name ON PLANS(USER_ID, NAME);