CREATE TABLE PLAN_EXERCISES(
	PLAN_ID UUID NOT NULL,
	EXERCISE_ID UUID NOT NULL,
    FOREIGN KEY (PLAN_ID) REFERENCES PLANS(id)
);

CREATE UNIQUE INDEX one_plan_id_one_exercise ON PLAN_EXERCISES(PLAN_ID, EXERCISE_ID);

