name: build docker images

on:
    workflow_run:
        workflows: ["unit-tests"]
        types:
            - completed
jobs:
    build:
        if: ${{github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service:
                    - auth_service
                    - plan_service
                    - email_service
                    - orchestration_service
                    - tracker_service
                    - exercise_service
        
        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image for ${{matrix.service}}
              working-directory: services/${{matrix.service}}
              run: docker build . -t likithh/${{matrix.service}}:latest
            - name: push the image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/${{matrix.service}}:latest
        
    build_and_push_gateway_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: build image for gateway
              working-directory: api_gateway/
              run:
                docker build . -t likithh/gateway:latest
            - name: push the image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/gateway:latest

    build_postgres_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: infrastructure/postgres/
              run: 
                docker build . -t likithh/postgres:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/postgres:latest
    build_auth_migrator_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: services/auth_service/migrator/
              run: 
                docker build . -t likithh/auth_migrator:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/auth_migrator:latest
    build_plan_migrator_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: services/plan_service/migrator/
              run: 
                docker build . -t likithh/plan_migrator:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/plan_migrator:latest
    build_tracker_migrator_image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: services/tracker_service/migrator/
              run: 
                docker build . -t likithh/tracker_migrator:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/tracker_migrator:latest
    build_exercise_migrator_image:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: services/exercise_service/migrator/
              run: 
                docker build . -t likithh/exercise_migrator:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/exercise_migrator:latest
    build_email_migrator_image:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v4
            - name: build docker image
              working-directory: services/email_service/migrator/
              run: 
                docker build . -t likithh/email_migrator:latest
            - name: push the docker image
              run: |
                docker login -u likithh -p ${{secrets.DOCKER_ACCESS_TOKEN}}
                docker push likithh/email_migrator:latest


