name: unit-tests

on:
    push:
        branches: 
            - "main"
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                service:
                - auth_service
                - email_service
                - exercise_service
                - orchestration_service
                - plan_service
                - tracker_service
        steps:
            - name: checkout
              uses: "actions/checkout@v4"
            - name: set up go
              uses: "actions/setup-go@v5"
              with:
                go-version: 1.25
            - name: run test
              working-directory: services/${{matrix.service}}
              run: |
                go mod tidy
                go test -v ./...

            
