name: unit-tests

on:
    push:
        branches: 
            - "main"

jobs:
    unit-test:
        runs-on: ubuntu-24.04
        steps:
            - uses: "actions/checkout@v4"
            - name: set up go 
              uses: "actions/setup-go@v5"
              with: 
                go-version : 1.25
            - name: auth unit tests
              working-directory: services/auth_service
              run : | 
                go mod tidy
                go test ./... -v
            - name: plan unit tests
              working-directory: services/plan_service
              run : |
                go mod tidy
                go test ./... -v
            - name: email unit tests
              working-directory: services/email_service
              run: |
                go mod tidy
                go test -v ./...
            - name: tracker unit tests
              working-directory: services/tracker_service
              run: |
                go mod tidy
                go test -v ./...
            - name: exercise unit tests
              working-directory: services/exercise_service
              run: |
                go mod tidy
                go test -v ./...
            - name: orchestraton unit tests
              working-directory: services/orchestration_service
              run: |
                go mod tidy
                go test -v ./...
            


            