// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PINGreq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PINGreq) Reset() {
	*x = PINGreq{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PINGreq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PINGreq) ProtoMessage() {}

func (x *PINGreq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PINGreq.ProtoReflect.Descriptor instead.
func (*PINGreq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

type PINGresp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PINGresp) Reset() {
	*x = PINGresp{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PINGresp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PINGresp) ProtoMessage() {}

func (x *PINGresp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PINGresp.ProtoReflect.Descriptor instead.
func (*PINGresp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

type SendUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUUID) Reset() {
	*x = SendUUID{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUUID) ProtoMessage() {}

func (x *SendUUID) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUUID.ProtoReflect.Descriptor instead.
func (*SendUUID) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SendUUID) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type GetNewAccessTokenResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NewAccessToken string                 `protobuf:"bytes,1,opt,name=new_access_token,json=newAccessToken,proto3" json:"new_access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNewAccessTokenResp) Reset() {
	*x = GetNewAccessTokenResp{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewAccessTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewAccessTokenResp) ProtoMessage() {}

func (x *GetNewAccessTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewAccessTokenResp.ProtoReflect.Descriptor instead.
func (*GetNewAccessTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetNewAccessTokenResp) GetNewAccessToken() string {
	if x != nil {
		return x.NewAccessToken
	}
	return ""
}

type SendUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserId) Reset() {
	*x = SendUserId{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserId) ProtoMessage() {}

func (x *SendUserId) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserId.ProtoReflect.Descriptor instead.
func (*SendUserId) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SendUserId) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type UserLogOutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogOutResp) Reset() {
	*x = UserLogOutResp{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogOutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogOutResp) ProtoMessage() {}

func (x *UserLogOutResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogOutResp.ProtoReflect.Descriptor instead.
func (*UserLogOutResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *UserLogOutResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UserLoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	UUID          string                 `protobuf:"bytes,5,opt,name=UUID,proto3" json:"UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResp) Reset() {
	*x = UserLoginResp{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResp) ProtoMessage() {}

func (x *UserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResp.ProtoReflect.Descriptor instead.
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *UserLoginResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserLoginResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserLoginResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UserLoginResp) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

type UserSignUpReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignUpReq) Reset() {
	*x = UserSignUpReq{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpReq) ProtoMessage() {}

func (x *UserSignUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpReq.ProtoReflect.Descriptor instead.
func (*UserSignUpReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *UserSignUpReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserSignUpResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSignUpResp) Reset() {
	*x = UserSignUpResp{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSignUpResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSignUpResp) ProtoMessage() {}

func (x *UserSignUpResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSignUpResp.ProtoReflect.Descriptor instead.
func (*UserSignUpResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *UserSignUpResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSignUpResp) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSignUpResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserSignUpResp) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\t\n" +
	"\aPINGreq\"\n" +
	"\n" +
	"\bPINGresp\"\x1e\n" +
	"\bSendUUID\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\"A\n" +
	"\x15GetNewAccessTokenResp\x12(\n" +
	"\x10new_access_token\x18\x01 \x01(\tR\x0enewAccessToken\"%\n" +
	"\n" +
	"SendUserId\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"*\n" +
	"\x0eUserLogOutResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"@\n" +
	"\fUserLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x8a\x01\n" +
	"\rUserLoginResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04UUID\x18\x05 \x01(\tR\x04UUID\"U\n" +
	"\rUserSignUpReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x89\x01\n" +
	"\x0eUserSignUpResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xaf\x02\n" +
	"\vAuthService\x12;\n" +
	"\n" +
	"UserSignUp\x12\x14.proto.UserSignUpReq\x1a\x15.proto.UserSignUpResp\"\x00\x128\n" +
	"\tUserLogin\x12\x13.proto.UserLoginReq\x1a\x14.proto.UserLoginResp\"\x00\x128\n" +
	"\n" +
	"UserLogOut\x12\x11.proto.SendUserId\x1a\x15.proto.UserLogOutResp\"\x00\x12D\n" +
	"\x11GetNewAccessToken\x12\x0f.proto.SendUUID\x1a\x1c.proto.GetNewAccessTokenResp\"\x00\x12)\n" +
	"\x04PING\x12\x0e.proto.PINGreq\x1a\x0f.proto.PINGresp\"\x00B\x0eZ\f/shared/authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_auth_proto_goTypes = []any{
	(*PINGreq)(nil),               // 0: proto.PINGreq
	(*PINGresp)(nil),              // 1: proto.PINGresp
	(*SendUUID)(nil),              // 2: proto.SendUUID
	(*GetNewAccessTokenResp)(nil), // 3: proto.GetNewAccessTokenResp
	(*SendUserId)(nil),            // 4: proto.SendUserId
	(*UserLogOutResp)(nil),        // 5: proto.UserLogOutResp
	(*UserLoginReq)(nil),          // 6: proto.UserLoginReq
	(*UserLoginResp)(nil),         // 7: proto.UserLoginResp
	(*UserSignUpReq)(nil),         // 8: proto.UserSignUpReq
	(*UserSignUpResp)(nil),        // 9: proto.UserSignUpResp
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_auth_proto_depIdxs = []int32{
	10, // 0: proto.UserSignUpResp.created_at:type_name -> google.protobuf.Timestamp
	8,  // 1: proto.AuthService.UserSignUp:input_type -> proto.UserSignUpReq
	6,  // 2: proto.AuthService.UserLogin:input_type -> proto.UserLoginReq
	4,  // 3: proto.AuthService.UserLogOut:input_type -> proto.SendUserId
	2,  // 4: proto.AuthService.GetNewAccessToken:input_type -> proto.SendUUID
	0,  // 5: proto.AuthService.PING:input_type -> proto.PINGreq
	9,  // 6: proto.AuthService.UserSignUp:output_type -> proto.UserSignUpResp
	7,  // 7: proto.AuthService.UserLogin:output_type -> proto.UserLoginResp
	5,  // 8: proto.AuthService.UserLogOut:output_type -> proto.UserLogOutResp
	3,  // 9: proto.AuthService.GetNewAccessToken:output_type -> proto.GetNewAccessTokenResp
	1,  // 10: proto.AuthService.PING:output_type -> proto.PINGresp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
